stages:
  - bundle
  - test
  - build
  - deploy 

bundle:
    image: node:alpine
    stage: bundle
    script:
        - npm install
        

build:
  image: docker:stable
  stage: build
  services:
    - docker:dind
  script:
    - docker login "$CI_REGISTRY"
    - docker build -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master