stages:
  - bundle
  - test
  - build
  - deploy 

bundle:
    image: node:alpine
    stage: bundle
    script:
        - npm install
        - npm run start

build:
  image: docker:stable
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master