stages:
  - bundle
  - test
  - build
  - deploy 

bundle:
    image: node:alpine
    stage: bundle
    script:
        - npm install
        

build:
  image: docker:stable
  stage: build
  services:
    - docker:dind
  script:
    - docker login registry.gitlab.com
    - docker -t registry.gitlab.com/jtorrealba3200/demo-autodevops .
    - docker push registry.gitlab.com/jtorrealba3200/demo-autodevops
  only:
    - master