kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: srvc-core
spec:
  replicas: 2
  template:
    metadata:
      name: backend
      labels:
        app: srvc-core
        role: backend
    spec:
      containers:
      - name: srvc-core
        image: registry.gitlab.com/jtorrealba3200/demo-autodevops:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

